######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 6 12:06:50 2010
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += skewDetection
CONFIG += qtestlib
