######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 6 12:12:04 2010
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += . ../..
INCLUDEPATH += . ../..

MUNIP_DIR = "../.."

# Input
SOURCES += main.cpp \
           $$MUNIP_DIR/DataWarehouse.cpp \
           $$MUNIP_DIR/horizontalrunlengthimage.cpp \
           $$MUNIP_DIR/imagewidget.cpp \
           $$MUNIP_DIR/mainwindow.cpp \
           $$MUNIP_DIR/processstep.cpp \
           $$MUNIP_DIR/projection.cpp \
           $$MUNIP_DIR/segments.cpp \
           $$MUNIP_DIR/sidebar.cpp \
           $$MUNIP_DIR/staff.cpp \
           $$MUNIP_DIR/tools.cpp

HEADERS += $$MUNIP_DIR/DataWarehouse.h \
           $$MUNIP_DIR/horizontalrunlengthimage.h \
           $$MUNIP_DIR/imagewidget.h \
           $$MUNIP_DIR/mainwindow.h \
           $$MUNIP_DIR/processstep.h \
           $$MUNIP_DIR/projection.h \
           $$MUNIP_DIR/segments.h \
           $$MUNIP_DIR/sidebar.h \
           $$MUNIP_DIR/staff.h \
           $$MUNIP_DIR/tools.h

CONFIG += qtestlib

MOC_DIR = .tmp
OBJECTS_DIR = .tmp

